In [ ]:
import torch
from torch.distributions.categorical import Categorical

In [40]:
def ER(num_nodes : int, r : int):
  # probability and graph matrices
  Prob = torch.rand(num_nodes, num_nodes)
  A = torch.zeros(num_nodes, num_nodes)


  A[Prob < r] = 1
  return A

In [41]:
def SBC(num_nodes : int, P=None, C=None):

  # Cluster assignment and Inter Cluster probabilities.
  if P is None:
    P = torch.rand(5)
  if C is None:
    C = torch.rand(5,5)

  # probability and graph matrices
  Prob = torch.rand(num_nodes, num_nodes)
  A = torch.zeros(num_nodes, num_nodes)

  # Categorical distribution to assign clusters to the nodes.
  dist = Categorical(probs=P)
  cluster = dist.sample_n(num_nodes)

  cluster_i = cluster.view(-1, 1).repeat(1, num_nodes)
  cluster_j = cluster.view(1, -1).repeat(num_nodes, 1)

  thresh = C[cluster_i, cluster_j]
  A [Prob < thresh] = 1
  A [Prob >= thresh] = 0
  return A

In [43]:
def PA(num_nodes : int, init_num_nodes : int):

    A = torch.zeros(num_nodes, num_nodes)

    # Initial fully connected nodes.
    A[:init_num_nodes, :init_num_nodes] = 1

    #iterative node addition
    for i in range(num_nodes - init_num_nodes):
      prob = torch.sum(A[:init_num_nodes + i, :init_num_nodes + i], 1)
      prob = prob / (torch.sum(prob))
      print(prob)
      rand = torch.rand(prob.shape[-1])
      s = torch.zeros(prob.shape[-1])
      s[rand  < prob] = 1
      s[rand >= prob] = 0
      A[init_num_nodes + i, :init_num_nodes + i] = s
      A[:init_num_nodes + i, init_num_nodes + i] = s
    return A



In [ ]:
ER(10, 0.2)

tensor([[1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
        [0., 1., 1., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [ ]:
SBC(10)

<ipython-input-22-36e86a393b32>:15: FutureWarning: `sample_n(n)` will be deprecated. Use `sample((n,))` instead.
  cluster = dist.sample_n(num_nodes)


tensor([[1., 1., 0., 1., 1., 0., 0., 1., 0., 1.],
        [1., 1., 1., 1., 0., 1., 0., 1., 1., 1.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 1., 1., 0., 1., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
        [0., 1., 1., 1., 0., 1., 0., 1., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 0., 1., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0., 1.]])

In [44]:
PA(10, 3)

tensor([0.3333, 0.3333, 0.3333])
tensor([0.2727, 0.2727, 0.3636, 0.0909])
tensor([0.2308, 0.3077, 0.3077, 0.0769, 0.0769])
tensor([0.2308, 0.3077, 0.3077, 0.0769, 0.0769, 0.0000])
tensor([0.2308, 0.3077, 0.3077, 0.0769, 0.0769, 0.0000, 0.0000])
tensor([0.2000, 0.3333, 0.2667, 0.0667, 0.0667, 0.0000, 0.0000, 0.0667])
tensor([0.2000, 0.3333, 0.2667, 0.0667, 0.0667, 0.0000, 0.0000, 0.0667, 0.0000])


tensor([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1., 0., 0., 1., 0., 1.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])